CLS
@ECHO OFF
COLOR 70
MODE CON COLS=80 LINES=25
SET Uninstall=start /wait MsiExec.exe /passive /norestart /uninstall
ECHO.
ECHO ------------------------------------------------------------------------------
ECHO.
ECHO      注意事項：
ECHO      1. 本程式將協助您移除 Windows Live 程式集 2012 所有相關元件，不做保留，
ECHO         如要離開請按 Ctrl+C。
ECHO      2. 請使用"以系統管理員身份執行"本批次檔，以免反覆跳出提示訊息，造成困擾。
ECHO      3. 本移除程式可移除下列版本的 Windows Live 程式集 2012，
ECHO           Build 16.4.3503.0728 繁體中文版
ECHO         如您安裝的不是上列版本，將不做任何異動。
ECHO      4. 已測試作業系統平台：
ECHO           Windows Vista x86 SP2 (全版本)
ECHO           Windows Vista x64 SP2 (全版本)
ECHO           Windows 7 x86 SP0, SP1 (全版本)
ECHO           Windows 7 x64 SP0, SP1 (全版本)
ECHO           Windows Server 2008 R2 SP1 (全版本)
ECHO         非支援平台(例如 Windows Server 2008 無印版)仍可使用，
ECHO         但可能會有未移除乾淨的元件。
ECHO                                                                三秒練功房製
ECHO                                                        更新日期：2012/11/25
ECHO ------------------------------------------------------------------------------
pause
ECHO.
ECHO      正在移除 Bing Bar Platform，請稍候...
"%ProgramFiles%\Bing Bar Installer\InstallManager.exe" /UNINSTALL /SILENT > nul
"%SystemDrive%\Program Files (x86)\Bing Bar Installer\InstallManager.exe" /UNINSTALL /SILENT  > nul
ECHO      正在移除 Junk Mail filter update，請稍候...

ECHO      正在移除 Mesh Runtime，請稍候...

ECHO      正在移除 Messenger 分享元件，請稍候...

ECHO      正在移除 Microsoft Application Error Reporting，請稍候...

ECHO      正在移除 Microsoft Search Enhancement Pack，請稍候...

ECHO      正在移除 Microsoft SQL Server 2005 Compact Edition [ENU]，請稍候...

ECHO      正在移除 MSVCRT，請稍候...

ECHO      正在移除 MSVCRT_amd64，請稍候...

ECHO      正在移除 Segoe UI，請稍候...

ECHO      正在移除 Windows Live Communications Platform，請稍候...

ECHO      正在移除 Windows Live Family Safety，請稍候...

ECHO      正在移除 Windows Live ID Sign-in Assistant，請稍候...

ECHO      正在移除 Windows Live Installer，請稍候...

ECHO      正在移除 Windows Live Language Selector，請稍候...

ECHO      正在移除 Windows Live Mail，請稍候...

ECHO      正在移除 Windows Live Mesh，請稍候...

ECHO      正在移除 Windows Live Messenger，請稍候...

ECHO      正在移除 Windows Live Messenger Companion Core，請稍候...

ECHO      正在移除 Windows Live MIME IFilter，請稍候...

ECHO      正在移除 Windows Live Movie Maker，請稍候...

ECHO      正在移除 Windows Live Photo Common，請稍候...

ECHO      正在移除 Windows Live Photo Gallery，請稍候...

ECHO      正在移除 Windows Live PIMT Platform，請稍候...

ECHO      正在移除 Windows Live Remote Client，請稍候...

ECHO      正在移除 Windows Live Remote Client Resources，請稍候...

ECHO      正在移除 Windows Live Remote Service，請稍候...

ECHO      正在移除 Windows Live Remote Service Resources，請稍候...

ECHO      正在移除 Windows Live SOXE，請稍候...

ECHO      正在移除 Windows Live SOXE Definitions，請稍候...

ECHO      正在移除 Windows Live UX Platform，請稍候...

ECHO      正在移除 Windows Live UX Platform Language Pack，請稍候...

ECHO      正在移除 Windows Live Writer，請稍候...

ECHO      正在移除 Windows Live Writer Resources，請稍候...

ECHO      正在移除 Windows Live 程式集，請稍候...

ECHO      正在移除 Windows Live 影像中心，請稍候...

ECHO      正在移除 D3DX10，請稍候...

ECHO      正在移除 適用遠端連線的 Windows Live Mesh ActiveX 控制項，請稍候...

ECHO      正在清除安裝檔案，請稍候...
rmdir /S /Q "%ProgramFiles%\Common Files\Windows Live" > nul
rmdir /S /Q "%SystemDrive%\Program Files (x86)\Common Files\Windows Live" > nul
ECHO ------------------------------------------------------------------------------
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO      全部移除完成，請按任意鍵關閉視窗，並自行重新開機。
ECHO      移除程式必須重新開機後才可生效。
ECHO.
ECHO.
ECHO.
ECHO.
PAUSE
Exit